### PR TITLE
Add parsing of inline LaTeX

### PR DESCRIPTION
**Pull request by martmists**

### CODE REVIEW

**Comment by gdude2002** [comment]
Just getting around to testing, and...

```py
  File "/home/leaf/PycharmProjects/bot/bot/cogs/math.py", line 89, in on_message
    for match in finditer(self.latex_regexp, message.content):
NameError: name 'finditer' is not defined
```

**Comment by gdude2002** [comment]
When I import finditer myself...

**Comment by martmists** [comment]
No clue why it's not connecting to latex2png, but I'm not the one who suggested that idea.... it *should* work though..

**Comment by martmists** [comment]
I added the API because you guys asked for it...... But I'll switch it back to the old one.

**Comment by martmists** [comment]
@1mn @gdude2002 Please review it soon, I don't update my branch all the time.

**Pull request closed without merging**
